In [1]:
%matplotlib inline
%load_ext autoreload
%autoreload 2

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import Markdown, display, HTML
from collections import defaultdict

# Fix the dying kernel problem (only a problem in some installations - you can remove it, if it works without it)
import os
os.environ['KMP_DUPLICATE_LIB_OK'] = 'True'

# Load the dataset for recommenders

In [3]:
data_path = os.path.join("data", "hotel_data")

interactions_df = pd.read_csv(os.path.join(data_path, "hotel_data_interactions_df.csv"), index_col=0)

base_item_features = ['term', 'length_of_stay_bucket', 'rate_plan', 'room_segment', 'n_people_bucket', 'weekend_stay']

column_values_dict = {
    'term': ['WinterVacation', 'Easter', 'OffSeason', 'HighSeason', 'LowSeason', 'MayLongWeekend', 'NewYear', 'Christmas'],
    'length_of_stay_bucket': ['[0-1]', '[2-3]', '[4-7]', '[8-inf]'],
    'rate_plan': ['Standard', 'Nonref'],
    'room_segment': ['[0-160]', '[160-260]', '[260-360]', '[360-500]', '[500-900]'],
    'n_people_bucket': ['[1-1]', '[2-2]', '[3-4]', '[5-inf]'],
    'weekend_stay': ['True', 'False']
}

interactions_df.loc[:, 'term'] = pd.Categorical(
    interactions_df['term'], categories=column_values_dict['term'])
interactions_df.loc[:, 'length_of_stay_bucket'] = pd.Categorical(
    interactions_df['length_of_stay_bucket'], categories=column_values_dict['length_of_stay_bucket'])
interactions_df.loc[:, 'rate_plan'] = pd.Categorical(
    interactions_df['rate_plan'], categories=column_values_dict['rate_plan'])
interactions_df.loc[:, 'room_segment'] = pd.Categorical(
    interactions_df['room_segment'], categories=column_values_dict['room_segment'])
interactions_df.loc[:, 'n_people_bucket'] = pd.Categorical(
    interactions_df['n_people_bucket'], categories=column_values_dict['n_people_bucket'])
interactions_df.loc[:, 'weekend_stay'] = interactions_df['weekend_stay'].astype('str')
interactions_df.loc[:, 'weekend_stay'] = pd.Categorical(
    interactions_df['weekend_stay'], categories=column_values_dict['weekend_stay'])

display(HTML(interactions_df.head(15).to_html()))

# Define user features based on reservations

The content-based recommenders will be forecasting the probability of interaction between user and item based on user features vector and item features vector:

<center>
$$
    r_{u, i} = f(user\_features, item\_features)
$$
</center>

<span style="color:red"><font size="4">**Task:**</font></span><br> 
Design numerical user features based on user reservations. Code the following method which for a given interactions DataFrame (it will be used in the fit method of the recommender) returns a DataFrame with user_id and user features as well as a list with names of user features (this will be important to select the right columns for an ML algorithm). Remember to name the columns differently than item features which you will create in the next task. Validate your features on users with several interactions (sample user ids are already given below).

Ideas for user features:
- Find the vector of most popular feature values from all user reservations and encode every feature with one-hot encoding.
- For every reservation feature calculate the probability distribution of its values among all user's reservations.
- For numerical buckets (length_of_stay, room_segment, n_people) you can calculate the average value for every user from their reservations (you will have to map the buckets back to numerical values before averaging them).

Remember that you will have to select the best features (with the highest explanatory power). Using all above features at once would make the number of variables too large for this dataset and would also introduce too much correlations between features.

You can also prepare several version of the prepare_users_df method and test which works best in your recommender.

In [4]:
def prepare_users_df(interactions_df):

    interactions_df = interactions_df.groupby(["user_id"]).agg(lambda x:x.value_counts(["term", "room_segment","rate_plan","weekend_stay","n_people_bucket"]).index[0])
    interactions_df = interactions_df.reset_index()
    interactions_df = interactions_df.drop(['item_id'], axis=1)
    users_df = pd.get_dummies(interactions_df, columns=['term','length_of_stay_bucket', 'room_segment',"rate_plan","weekend_stay","n_people_bucket"])
    users_df.columns = [str(col) + '_users' for col in users_df.columns]
    user_features = list(users_df.columns)
    #user_features = users_df.columns

    users_df.rename(columns={'user_id_users':'user_id'}, inplace=True)
    user_features.remove('user_id_users')
    
    
    return users_df, user_features
    

users_df, user_features = prepare_users_df(interactions_df)

print(user_features)

display(HTML(users_df.loc[users_df['user_id'].isin([706, 1736, 7779, 96, 1, 50, 115])].head(15).to_html()))

['term_Christmas_users', 'term_Easter_users', 'term_HighSeason_users', 'term_LowSeason_users', 'term_MayLongWeekend_users', 'term_NewYear_users', 'term_OffSeason_users', 'term_WinterVacation_users', 'length_of_stay_bucket_[0-1]_users', 'length_of_stay_bucket_[2-3]_users', 'length_of_stay_bucket_[4-7]_users', 'length_of_stay_bucket_[8-inf]_users', 'room_segment_[0-160]_users', 'room_segment_[160-260]_users', 'room_segment_[260-360]_users', 'room_segment_[360-500]_users', 'room_segment_[500-900]_users', 'rate_plan_Nonref_users', 'rate_plan_Standard_users', 'weekend_stay_False_users', 'weekend_stay_True_users', 'n_people_bucket_[1-1]_users', 'n_people_bucket_[2-2]_users', 'n_people_bucket_[3-4]_users', 'n_people_bucket_[5-inf]_users']


# Prepare numerical item features

<span style="color:red"><font size="4">**Task:**</font></span><br> 
Code the prepare_items_df method which will be used in the recommender fit and recommend methods to map items to numerical features. This method should take the interactions_df DataFrame as input and return a DataFrame containing one record per item_id with item_id column and numerical item feature columns.

You can try turning all item features into on-hot representations. You can use the get_dummies method from pandas. It will return the same columns on any dataset of interactions because of the categorical variables with all possible values have been defined in the second cell in this notebook.

You are welcome to design your own numerical item features.

In [147]:
def prepare_items_df(interactions_df):
    
    interactions_df = interactions_df.groupby(["item_id"]).agg(lambda x:x.value_counts(["term", "room_segment","rate_plan","weekend_stay","n_people_bucket"]).index[0])
   
    interactions_df = interactions_df.reset_index()
    interactions_df = interactions_df.drop(['user_id'], axis=1)
    items_df = pd.get_dummies(interactions_df, columns=['term','length_of_stay_bucket', 'room_segment',"rate_plan","weekend_stay","n_people_bucket"])
    items_df.columns = ['items_' + str(col) for col in items_df.columns]
    item_features = list(items_df.columns)
    item_features.remove('items_item_id')
    items_df.rename(columns={'items_item_id':'item_id'}, inplace=True)
    return items_df, item_features



items_df, item_features = prepare_items_df(interactions_df)

print(item_features)

display(HTML(items_df.loc[items_df['item_id'].isin([0, 1, 2, 3, 4, 5, 6])].head(15).to_html()))

['items_term_Christmas', 'items_term_Easter', 'items_term_HighSeason', 'items_term_LowSeason', 'items_term_MayLongWeekend', 'items_term_NewYear', 'items_term_OffSeason', 'items_term_WinterVacation', 'items_length_of_stay_bucket_[0-1]', 'items_length_of_stay_bucket_[2-3]', 'items_length_of_stay_bucket_[4-7]', 'items_length_of_stay_bucket_[8-inf]', 'items_room_segment_[0-160]', 'items_room_segment_[160-260]', 'items_room_segment_[260-360]', 'items_room_segment_[360-500]', 'items_room_segment_[500-900]', 'items_rate_plan_Nonref', 'items_rate_plan_Standard', 'items_weekend_stay_False', 'items_weekend_stay_True', 'items_n_people_bucket_[1-1]', 'items_n_people_bucket_[2-2]', 'items_n_people_bucket_[3-4]', 'items_n_people_bucket_[5-inf]']


In [6]:
def prepare_items_df_2(interactions_df):
    
    interactions_df = interactions_df.groupby(["item_id"]).agg(lambda x:x.value_counts(["term", "room_segment","rate_plan","weekend_stay","n_people_bucket"]).index[0])
   
    interactions_df = interactions_df.reset_index()
    items_df = pd.get_dummies(interactions_df, columns=['term','length_of_stay_bucket', 'room_segment',"rate_plan","weekend_stay","n_people_bucket"])
    items_df.columns = ['items_' + str(col) for col in items_df.columns]
    item_features = list(items_df.columns)
    item_features.remove('items_item_id')
    items_df.rename(columns={'items_item_id':'item_id'}, inplace=True)
    return items_df, item_features

In [149]:
start = time.time()

items_df, item_features = prepare_items_df_2(interactions_df)
end = time.time()
print(end - start)

6.413151502609253


In [7]:
items_df

item_id  items_term_Christmas  items_term_Easter  items_term_HighSeason  \
0           0                     0                  0                      0   
1           1                     0                  0                      0   
2           2                     0                  0                      0   
3           3                     0                  0                      0   
4           4                     0                  0                      0   
...       ...                   ...                ...                    ...   
1069     1069                     0                  0                      0   
1070     1070                     0                  0                      0   
1071     1071                     0                  0                      0   
1072     1072                     0                  0                      0   
1073     1073                     0                  0                      0   

      items_term_LowSeason  items_term_MayLongWeekend  items_term_NewYear  \
0                        0                          0                   0   
1                        0                          0                   0   
2                        0                          0                   0   
3                        0                          0                   0   
4                        0                          0                   0   
...                    ...                        ...                 ...   
1069                     0                          0                   0   
1070                     0                          0                   1   
1071                     0                          0                   1   
1072                     0                          0                   1   
1073                     0                          0                   0   

      items_term_OffSeason  items_term_WinterVacation  \
0                        0                          1   
1                        0                          1   
2                        0                          1   
3                        0                          1   
4                        0                          1   
...                    ...                        ...   
1069                     0                          1   
1070                     0                          0   
1071                     0                          0   
1072                     0                          0   
1073                     1                          0   

      items_length_of_stay_bucket_[0-1]  ...  items_room_segment_[360-500]  \
0                                     0  ...                             0   
1                                     0  ...                             0   
2                                     0  ...                             0   
3                                     0  ...                             0   
4                                     0  ...                             0   
...                                 ...  ...                           ...   
1069                                  0  ...                             0   
1070                                  0  ...                             1   
1071                                  0  ...                             1   
1072                                  1  ...                             0   
1073                                  0  ...                             0   

      items_room_segment_[500-900]  items_rate_plan_Nonref  \
0                                0                       0   
1                                0                       0   
2                                0                       0   
3                                0                       0   
4                                0                       0   
...                            ...                     ...   
1069                             0                  

In [8]:
item_features

['items_term_Christmas',
 'items_term_Easter',
 'items_term_HighSeason',
 'items_term_LowSeason',
 'items_term_MayLongWeekend',
 'items_term_NewYear',
 'items_term_OffSeason',
 'items_term_WinterVacation',
 'items_length_of_stay_bucket_[0-1]',
 'items_length_of_stay_bucket_[2-3]',
 'items_length_of_stay_bucket_[4-7]',
 'items_length_of_stay_bucket_[8-inf]',
 'items_room_segment_[0-160]',
 'items_room_segment_[160-260]',
 'items_room_segment_[260-360]',
 'items_room_segment_[360-500]',
 'items_room_segment_[500-900]',
 'items_rate_plan_Nonref',
 'items_rate_plan_Standard',
 'items_weekend_stay_False',
 'items_weekend_stay_True',
 'items_n_people_bucket_[1-1]',
 'items_n_people_bucket_[2-2]',
 'items_n_people_bucket_[3-4]',
 'items_n_people_bucket_[5-inf]']

# Content-based recommender

<span style="color:red"><font size="4">**Task:**</font></span><br> 
Code the content-based recommender. User features should be calculated within the fit method based on available training data and should be saved in the object for later use in the recommend method. Overwrite the users_df variable. Item features should be calculated both in the fit method (from interactions_df) and in the recommend method (from items_df - the items to be evaluated).

In the fit method you have to randomly generate non-existing interactions and add them to the training data for the regressor. You should add the target variable to interactions - equal to 1 for real interactions and equal to 0 for those newly added interactions. Generate several negative interactions per every positive interactions (n_neg_per_pos). Treat the proportion as a tunable parameter of the model.

Remember to keep control over randomness - in the init method add seed as a parameter and use initialize the random seed generator with that seed:

```python
self.seed = seed
self.rng = np.random.RandomState(seed=seed)
```

Below the base content-based recommender class there are several classes which inherit from the base class and use different ML models:
  - LinearRegressionCBUIRecommender - based on linear regression,
  - SVRCBUIRecommender - based on Support Vector Regressor (if you want to test it, sample the data in the fit method, as the training can take many hours on the entire dataset of interactions),
  - RandomForestCBUIRecommender - based on Random Forest,
  - XGBoostCBUIRecommender - based on XGBoost.
  
There is no need to change anything in those inheriting classes, although you can experiment with other tunable parameters of the underlying models.

You are encouraged to experiment with:
  - Other numerical user and item features (but always train and evaluate the model on buckets defined in the first notebook).
  - Other ML models, e.g. Huber regression, Lasso regression, Ridge regression, LARS regression, Linear SVR, Decision Tree, Naive Bayes, Neural Networks or any model of your choice.
  - A different approach where you treat each item as a class, you train directly on categorical features of items and users (you would have to design appropriate categorical features for users) and you fit classifiers (e.g. Decision Tree classifier, Naive Bayes classifier etc.) instead of regressors.

In [9]:
import random
import time
import itertools
def fill_it(interactions_df, negative_interactions, n_neg_per_pos):  
    arr = interactions_df[['user_id', 'item_id']].to_numpy()
    how_long = n_neg_per_pos * len(interactions_df)
    
    while len(negative_interactions) < how_long:
        a = random.randint(0,interactions_df.item_id.max())
        b = random.randint(0,interactions_df.user_id.max())
        if not([a,b] == arr).all(axis = 1).any():
            negative_interactions.append((a,b,0))
    return negative_interactions

In [10]:
items_df

item_id  items_term_Christmas  items_term_Easter  items_term_HighSeason  \
0           0                     0                  0                      0   
1           1                     0                  0                      0   
2           2                     0                  0                      0   
3           3                     0                  0                      0   
4           4                     0                  0                      0   
...       ...                   ...                ...                    ...   
1069     1069                     0                  0                      0   
1070     1070                     0                  0                      0   
1071     1071                     0                  0                      0   
1072     1072                     0                  0                      0   
1073     1073                     0                  0                      0   

      items_term_LowSeason  items_term_MayLongWeekend  items_term_NewYear  \
0                        0                          0                   0   
1                        0                          0                   0   
2                        0                          0                   0   
3                        0                          0                   0   
4                        0                          0                   0   
...                    ...                        ...                 ...   
1069                     0                          0                   0   
1070                     0                          0                   1   
1071                     0                          0                   1   
1072                     0                          0                   1   
1073                     0                          0                   0   

      items_term_OffSeason  items_term_WinterVacation  \
0                        0                          1   
1                        0                          1   
2                        0                          1   
3                        0                          1   
4                        0                          1   
...                    ...                        ...   
1069                     0                          1   
1070                     0                          0   
1071                     0                          0   
1072                     0                          0   
1073                     1                          0   

      items_length_of_stay_bucket_[0-1]  ...  items_room_segment_[360-500]  \
0                                     0  ...                             0   
1                                     0  ...                             0   
2                                     0  ...                             0   
3                                     0  ...                             0   
4                                     0  ...                             0   
...                                 ...  ...                           ...   
1069                                  0  ...                             0   
1070                                  0  ...                             1   
1071                                  0  ...                             1   
1072                                  1  ...                             0   
1073                                  0  ...                             0   

      items_room_segment_[500-900]  items_rate_plan_Nonref  \
0                                0                       0   
1                                0                       0   
2                                0                       0   
3                                0                       0   
4                                0                       0   
...                            ...                     ...   
1069                             0                  

In [114]:
for ix, user in users_df.iterrows():
    user = user.to_frame().T
    print(user)
    print(user['user_id'][0])

    
    
   # print(user['user_id'])
    break

   user_id  term_Christmas_users  term_Easter_users  term_HighSeason_users  \
0        1                     0                  0                      0   

   term_LowSeason_users  term_MayLongWeekend_users  term_NewYear_users  \
0                     0                          0                   0   

   term_OffSeason_users  term_WinterVacation_users  \
0                     1                          0   

   length_of_stay_bucket_[0-1]_users  ...  room_segment_[360-500]_users  \
0                                  0  ...                             0   

   room_segment_[500-900]_users  rate_plan_Nonref_users  \
0                             0                       0   

   rate_plan_Standard_users  weekend_stay_False_users  \
0                         1                         0   

   weekend_stay_True_users  n_people_bucket_[1-1]_users  \
0                        1                            0   

   n_people_bucket_[2-2]_users  n_people_bucket_[3-4]_users  \
0                 

In [178]:
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingRegressor

from recommenders.recommender import Recommender


class ContentBasedUserItemRecommender(Recommender):
    """
    Linear recommender class based on user and item features.
    """
    
    def __init__(self, seed=6789, n_neg_per_pos=5):
        """
        Initialize base recommender params and variables.
        """
        self.model = LinearRegression()
        self.n_neg_per_pos = n_neg_per_pos
        
        self.recommender_df = pd.DataFrame(columns=['user_id', 'item_id', 'score'])
        self.users_df = None
        self.user_features = None
        
        self.seed = seed
        self.rng = np.random.RandomState(seed=seed)
    
    def fit(self, interactions_df, users_df, items_df):
        """
        Training of the recommender.
        
        :param pd.DataFrame interactions_df: DataFrame with recorded interactions between users and items 
            defined by user_id, item_id and features of the interaction.
        :param pd.DataFrame users_df: DataFrame with users and their features defined by user_id and the user feature columns.
        :param pd.DataFrame items_df: DataFrame with items and their features defined by item_id and the item feature columns.
        """
        
        interactions_df = interactions_df.copy()
        
        # Prepare users_df and items_df
        
        users_df, user_features = prepare_users_df(interactions_df)
        
        self.users_df = users_df
        self.user_features = user_features
        
       
        
        items_df, item_features = prepare_items_df(interactions_df)
        items_df = items_df.loc[:, ['item_id'] + item_features]
        
        # Generate negative interactions
        
        interactions_df = interactions_df.loc[:, ['user_id', 'item_id']]
        
        interactions_df.loc[:, 'interacted'] = 1
        
        negative_interactions = []
        
        # Write your code here
        
        # Generate tuples (user_id, item_id, 0) for pairs (user_id, item_id) which do not
        # appear in the interactions_df and add those tuples to the list negative_interactions.
        # Generate self.n_neg_per_pos * len(interactions_df) negative interactions 
        # (self.n_neg_per_pos per one positive).
        # Make sure the code is efficient and runs fast, otherwise you will not be able to properly tune your model.

        negative_interactions = fill_it(interactions_df, negative_interactions, self.n_neg_per_pos)

        
        interactions_df = pd.concat(
            [interactions_df, pd.DataFrame(negative_interactions, columns=['user_id', 'item_id', 'interacted'])])
        
        # Get the input data for the model
        
        interactions_df = pd.merge(interactions_df, users_df, on=['user_id'])
        
        interactions_df = pd.merge(interactions_df, items_df, on=['item_id'])
        
        x = interactions_df.loc[:, user_features + item_features].values
        y = interactions_df['interacted'].values
    
        self.model.fit(x, y)
    
    def recommend(self, users_df, items_df, n_recommendations=1):
        """
        Serving of recommendations. Scores items in items_df for each user in users_df and returns 
        top n_recommendations for each user.
        
        :param pd.DataFrame users_df: DataFrame with users and their features for which recommendations should be generated.
        :param pd.DataFrame items_df: DataFrame with items and their features which should be scored.
        :param int n_recommendations: Number of recommendations to be returned for each user.
        :return: DataFrame with user_id, item_id and score as columns returning n_recommendations top recommendations 
            for each user.
        :rtype: pd.DataFrame
        """
        
        # Clean previous recommendations (iloc could be used alternatively)
        self.recommender_df = self.recommender_df[:0]
        
        # Write your code here
        # Prepare users_df and items_df
        
        users_df = pd.merge(self.users_df, users_df)
        # For users_df you just need to merge user features from self.users_df to users_df 
        # (the users for which you generate recommendations)
        # For items you have to apply the prepare_items_df method to items_df.
        #items_df, featuredsa = prepare_items_df_2(items_df)
        #print(items_df)
        # Score the items
        recommendations = pd.DataFrame(columns=['user_id', 'item_id', 'score'])
        
        for ix, user in users_df.iterrows():
            # Write your code here
            # Create a Carthesian product of users from users_df and items from items_df
            records = []
            user_one = user.to_frame().T
            cart_list = pd.merge(user_one,items_df, how='cross')
            #cart_list = pd.merge(user,items_df, left_on='user_id' , right_on='item_id') #how='cross')
            cart_list_predict = cart_list.drop(['item_id', 'user_id', 'items_user_id'], axis=1, errors='ignore')
            #print(cart_list)
            #print(cart_list)
            #print(cart_list['user_id'])
            #print(cart_list['user_id'][0])
            #cart_list['user_id'] = cart_list['user_id'][0] 
            scores = self.model.predict(cart_list_predict)
            #print(scores)
            
            chosen_ids = None
            ids = (-scores).argsort()[:n_recommendations]
            chosen_ids = cart_list.iloc[ids]['item_id']
            
            
            
            #             cart = itertools.product(users_df.user_id, items_df.item_id)
#             cart_list = []
#             for v in cart:
#                 cart_list.append(v)
#                 record = self.model.predict(cart_list)
#                 records.append(record)
            # Write your code here
            # Use self.model.predict method to calculate scores for all records in the just created DataFrame
            # of users and items
            
            
            
            # Write your code here
            # Obtain item ids with the highest score and save those ids under the chosen_ids variable
            # Do not exclude already booked items.
            
            
            recommendations = []
            for item_id in chosen_ids:
                recommendations.append(
                    {
                        'user_id': user['user_id'],
                        'item_id': item_id,
                        'score': scores[item_id]
                    }
                )
            
            user_recommendations = pd.DataFrame(recommendations)

            self.recommender_df = pd.concat([self.recommender_df, user_recommendations])

        return self.recommender_df
    
    
class LinearRegressionCBUIRecommender(ContentBasedUserItemRecommender):
    """
    Linear regression recommender class based on user and item features.
    """
    
    def __init__(self, seed=6789, n_neg_per_pos=5, **model_params):
        """
        Initialize base recommender params and variables.
        """
        super().__init__(seed=seed, n_neg_per_pos=n_neg_per_pos)
        self.model = LinearRegression()
        
        
class SVRCBUIRecommender(ContentBasedUserItemRecommender):
    """
    SVR recommender class based on user and item features.
    """
    
    def __init__(self, seed=6789, n_neg_per_pos=5, **model_params):
        """
        Initialize base recommender params and variables.
        """
        super().__init__(seed=seed, n_neg_per_pos=n_neg_per_pos)
        if 'kernel' in model_params:
            self.kernel = model_params['kernel']
        else:
            self.kernel = 'rbf'
        if 'C' in model_params:
            self.C = model_params['C']
        else:
            self.C = 1.0
        if 'epsilon' in model_params:
            self.epsilon = model_params['epsilon']
        else:
            self.epsilon = 0.1
        self.model = SVR(kernel=self.kernel, C=self.C, epsilon=self.epsilon)
        
    
class RandomForestCBUIRecommender(ContentBasedUserItemRecommender):
    """
    Random forest recommender class based on user and item features.
    """
    
    def __init__(self, seed=6789, n_neg_per_pos=5, **model_params):
        """
        Initialize base recommender params and variables.
        """
        super().__init__(seed=seed, n_neg_per_pos=n_neg_per_pos)
        if 'n_estimators' in model_params:
            self.n_estimators = int(model_params['n_estimators'])
        else:
            self.n_estimators = 100
        if 'max_depth' in model_params:
            self.max_depth = int(model_params['max_depth'])
        else:
            self.max_depth = 30
        if 'min_samples_split' in model_params:
            self.min_samples_split = int(model_params['min_samples_split'])
        else:
            self.min_samples_split = 30
        self.model = RandomForestRegressor(
            n_estimators=self.n_estimators, max_depth=self.max_depth, min_samples_split=self.min_samples_split)
    
    
class XGBoostCBUIRecommender(ContentBasedUserItemRecommender):
    """
    XGBoost recommender class based on user and item features.
    """
    
    def __init__(self, seed=6789, n_neg_per_pos=5, **model_params):
        """
        Initialize base recommender params and variables.
        """
        super().__init__(seed=seed, n_neg_per_pos=n_neg_per_pos)
        if 'n_estimators' in model_params:
            self.n_estimators = int(model_params['n_estimators'])
        else:
            self.n_estimators = 100
        if 'max_depth' in model_params:
            self.max_depth = int(model_params['max_depth'])
        else:
            self.max_depth = 30
        if 'min_samples_split' in model_params:
            self.min_samples_split = int(model_params['min_samples_split'])
        else:
            self.min_samples_split = 30
        if 'learning_rate' in model_params:
            self.learning_rate = model_params['learning_rate']
        else:
            self.learning_rate = 30
        self.model = GradientBoostingRegressor(
            n_estimators=self.n_estimators, max_depth=self.max_depth, min_samples_split=self.min_samples_split,
            learning_rate=self.learning_rate)    

# Quick test of the recommender

In [159]:
items_df = interactions_df.loc[:, ['item_id'] + base_item_features].drop_duplicates()

In [160]:
items_df, featuredsa = prepare_items_df_2(items_df)

In [161]:
items_df

item_id  items_term_Christmas  items_term_Easter  items_term_HighSeason  \
0           0                     0                  0                      0   
1           1                     0                  0                      0   
2           2                     0                  0                      0   
3           3                     0                  0                      0   
4           4                     0                  0                      0   
...       ...                   ...                ...                    ...   
1069     1069                     0                  0                      0   
1070     1070                     0                  0                      0   
1071     1071                     0                  0                      0   
1072     1072                     0                  0                      0   
1073     1073                     0                  0                      0   

      items_term_LowSeason  items_term_MayLongWeekend  items_term_NewYear  \
0                        0                          0                   0   
1                        0                          0                   0   
2                        0                          0                   0   
3                        0                          0                   0   
4                        0                          0                   0   
...                    ...                        ...                 ...   
1069                     0                          0                   0   
1070                     0                          0                   1   
1071                     0                          0                   1   
1072                     0                          0                   1   
1073                     0                          0                   0   

      items_term_OffSeason  items_term_WinterVacation  \
0                        0                          1   
1                        0                          1   
2                        0                          1   
3                        0                          1   
4                        0                          1   
...                    ...                        ...   
1069                     0                          1   
1070                     0                          0   
1071                     0                          0   
1072                     0                          0   
1073                     1                          0   

      items_length_of_stay_bucket_[0-1]  ...  items_room_segment_[360-500]  \
0                                     0  ...                             0   
1                                     0  ...                             0   
2                                     0  ...                             0   
3                                     0  ...                             0   
4                                     0  ...                             0   
...                                 ...  ...                           ...   
1069                                  0  ...                             0   
1070                                  0  ...                             1   
1071                                  0  ...                             1   
1072                                  1  ...                             0   
1073                                  0  ...                             0   

      items_room_segment_[500-900]  items_rate_plan_Nonref  \
0                                0                       0   
1                                0                       0   
2                                0                       0   
3                                0                       0   
4                                0                       0   
...                            ...                     ...   
1069                             0                  

In [163]:
# Fit method
cb_user_item_recommender = RandomForestCBUIRecommender()
cb_user_item_recommender.fit(interactions_df, None, None)

In [164]:
# Recommender method

recommendations = cb_user_item_recommender.recommend(pd.DataFrame([[1], [2], [3], [4], [5]], columns=['user_id']), items_df, 10)

recommendations = pd.merge(recommendations, items_df, on='item_id', how='left')
display(HTML(recommendations.to_html()))

start_recomend
      item_id  items_term_Christmas  items_term_Easter  items_term_HighSeason  \
0           0                     0                  0                      0   
1           1                     0                  0                      0   
2           2                     0                  0                      0   
3           3                     0                  0                      0   
4           4                     0                  0                      0   
...       ...                   ...                ...                    ...   
1069     1069                     0                  0                      0   
1070     1070                     0                  0                      0   
1071     1071                     0                  0                      0   
1072     1072                     0                  0                      0   
1073     1073                     0                  0                      0   

      items_

# Tuning method

In [143]:
from evaluation_and_testing.testing import evaluate_train_test_split_implicit

seed = 6789

In [144]:
from hyperopt import hp, fmin, tpe, Trials
import traceback

def tune_recommender(recommender_class, interactions_df, items_df, 
                     param_space, max_evals=1, show_progressbar=True, seed=6789):
    # Split into train_validation and test sets

    shuffle = np.arange(len(interactions_df))
    rng = np.random.RandomState(seed=seed)
    rng.shuffle(shuffle)
    shuffle = list(shuffle)

    train_test_split = 0.8
    split_index = int(len(interactions_df) * train_test_split)

    train_validation = interactions_df.iloc[shuffle[:split_index]]
    test = interactions_df.iloc[shuffle[split_index:]]

    # Tune

    def loss(tuned_params):
        recommender = recommender_class(seed=seed, **tuned_params)
        hr1, hr3, hr5, hr10, ndcg1, ndcg3, ndcg5, ndcg10 = evaluate_train_test_split_implicit(
            recommender, train_validation, items_df, seed=seed)
        return -hr10

    n_tries = 1
    succeded = False
    try_id = 0
    while not succeded and try_id < n_tries:
        try:
            trials = Trials()
            best_param_set = fmin(loss, space=param_space, algo=tpe.suggest, 
                                  max_evals=max_evals, show_progressbar=show_progressbar, trials=trials, verbose=True)
            succeded = True
        except:
            traceback.print_exc()
            try_id += 1
            
    if not succeded:
        return None
        
    # Validate
    
    recommender = recommender_class(seed=seed, **best_param_set)

    results = [[recommender_class.__name__] + list(evaluate_train_test_split_implicit(
        recommender, {'train': train_validation, 'test': test}, items_df, seed=seed))]

    results = pd.DataFrame(results, 
                           columns=['Recommender', 'HR@1', 'HR@3', 'HR@5', 'HR@10', 'NDCG@1', 'NDCG@3', 'NDCG@5', 'NDCG@10'])

    display(HTML(results.to_html()))
    
    return best_param_set

## Tuning of the recommender

<span style="color:red"><font size="4">**Task:**</font></span><br> 
Tune your models using the code below. You only need to put the class name of your recommender and choose an appropriate parameter space.

In [167]:
items_df, featuredsa = prepare_items_df_2(items_df)

KeyError: "None of [Index(['term', 'length_of_stay_bucket', 'room_segment', 'rate_plan',\n       'weekend_stay', 'n_people_bucket'],\n      dtype='object')] are in the [columns]"

In [179]:
param_space = {
    'n_neg_per_pos': hp.quniform('n_neg_per_pos', 1, 10, 1)
}

best_param_set = tune_recommender(LinearRegressionCBUIRecommender, interactions_df, items_df,
                                  param_space, max_evals=10, show_progressbar=True, seed=seed)

print("Best parameters:")
print(best_param_set)

100%|████████████████████████████████████████████| 10/10 [25:25<00:00, 152.58s/trial, best loss: -0.022531749283080705]


Best parameters:
{'n_neg_per_pos': 9.0}


In [ ]:
param_space = {
    'n_neg_per_pos': hp.quniform('n_neg_per_pos', 1, 10, 1),
    'C': hp.loguniform('C', np.log(0.01), np.log(100.0))
}

best_param_set = tune_recommender(SVRCBUIRecommender, interactions_df, items_df,
                                  param_space, max_evals=100, show_progressbar=True, seed=seed)

print("Best parameters:")
print(best_param_set)

  0%|                                                                          | 0/100 [00:00<?, ?trial/s, best loss=?]

In [181]:
param_space = {
    'n_neg_per_pos': hp.quniform('n_neg_per_pos', 1, 10, 1),
    'n_estimators': hp.quniform('n_estimators', 30, 300, 1),
    'max_depth': hp.quniform('max_depth', 2, 10, 1),
    'min_samples_split': hp.quniform('min_samples_split', 2, 30, 1)
}

best_param_set = tune_recommender(RandomForestCBUIRecommender, interactions_df, items_df,
                                  param_space, max_evals=100, show_progressbar=True, seed=seed)

print("Best parameters:")
print(best_param_set)

  1%|▍                                         | 1/100 [03:54<6:26:13, 234.08s/trial, best loss: -0.010241704219582138]
Best parameters:
None


Traceback (most recent call last):
  File "<ipython-input-144-164530239fdf>", line 33, in tune_recommender
    best_param_set = fmin(loss, space=param_space, algo=tpe.suggest,
  File "D:\Programs\conda\lib\site-packages\hyperopt\fmin.py", line 507, in fmin
    return trials.fmin(
  File "D:\Programs\conda\lib\site-packages\hyperopt\base.py", line 682, in fmin
    return fmin(
  File "D:\Programs\conda\lib\site-packages\hyperopt\fmin.py", line 553, in fmin
    rval.exhaust()
  File "D:\Programs\conda\lib\site-packages\hyperopt\fmin.py", line 356, in exhaust
    self.run(self.max_evals - n_done, block_until_done=self.asynchronous)
  File "D:\Programs\conda\lib\site-packages\hyperopt\fmin.py", line 292, in run
    self.serial_evaluate()
  File "D:\Programs\conda\lib\site-packages\hyperopt\fmin.py", line 170, in serial_evaluate
    result = self.domain.evaluate(spec, ctrl)
  File "D:\Programs\conda\lib\site-packages\hyperopt\base.py", line 907, in evaluate
    rval = self.fn(pyll_rval)
  F

In [20]:
# This tuning may take around 12 hours

param_space = {
    'n_neg_per_pos': hp.quniform('n_neg_per_pos', 1, 10, 1),
    'n_estimators': hp.quniform('n_estimators', 10, 300, 1),
    'max_depth': hp.quniform('max_depth', 2, 10, 1),
    'min_samples_split': hp.quniform('min_samples_split', 2, 30, 1),
    'learning_rate': hp.loguniform('learning_rate', np.log(0.001), np.log(0.1))
}

best_param_set = tune_recommender(XGBoostCBUIRecommender, interactions_df, items_df,
                                  param_space, max_evals=300, show_progressbar=True, seed=seed)

print("Best parameters:")
print(best_param_set)

my_function                                                                                                            
8.047999620437622                                                                                                      
  0%|                                                                          | 0/300 [01:03<?, ?trial/s, best loss=?]

job exception: "['items_user_id'] not found in axis"



  0%|                                                                          | 0/300 [01:14<?, ?trial/s, best loss=?]
Best parameters:
None


Traceback (most recent call last):
  File "<ipython-input-16-164530239fdf>", line 33, in tune_recommender
    best_param_set = fmin(loss, space=param_space, algo=tpe.suggest,
  File "D:\Programs\conda\lib\site-packages\hyperopt\fmin.py", line 507, in fmin
    return trials.fmin(
  File "D:\Programs\conda\lib\site-packages\hyperopt\base.py", line 682, in fmin
    return fmin(
  File "D:\Programs\conda\lib\site-packages\hyperopt\fmin.py", line 553, in fmin
    rval.exhaust()
  File "D:\Programs\conda\lib\site-packages\hyperopt\fmin.py", line 356, in exhaust
    self.run(self.max_evals - n_done, block_until_done=self.asynchronous)
  File "D:\Programs\conda\lib\site-packages\hyperopt\fmin.py", line 292, in run
    self.serial_evaluate()
  File "D:\Programs\conda\lib\site-packages\hyperopt\fmin.py", line 170, in serial_evaluate
    result = self.domain.evaluate(spec, ctrl)
  File "D:\Programs\conda\lib\site-packages\hyperopt\base.py", line 907, in evaluate
    rval = self.fn(pyll_rval)
  Fi

# Final evaluation

<span style="color:red"><font size="4">**Task:**</font></span><br> 
Run the final evaluation of your recommender and present its results against the Amazon recommender's results. You can present results for several of your recommenders. You just need to give the class name of your recommender and its tuned parameters below. If you present results for several recommenders, you should add a separate cell for each recommender and change the names of the DataFrames containing results.

In [174]:
cb_user_item_recommender = LinearRegressionCBUIRecommender(
    **{'n_neg_per_pos': 9})  # Initialize your recommender here with the best params from tuning

# Give the name of your recommender in the line below
linear_cbui_tts_results = [['LinearRegressionCBUIRecommender'] + list(evaluate_train_test_split_implicit(
    cb_user_item_recommender, interactions_df, items_df))]

linear_cbui_tts_results = pd.DataFrame(
    linear_cbui_tts_results, columns=['Recommender', 'HR@1', 'HR@3', 'HR@5', 'HR@10', 'NDCG@1', 'NDCG@3', 'NDCG@5', 'NDCG@10'])

display(HTML(linear_cbui_tts_results.to_html()))

start_recomend
[ 0.59887695  0.74633789  0.56518555 ... -0.35449219 -0.25415039
  0.49414062]
start_recomend
[1.13378906 1.28149414 1.1003418  ... 0.18115234 0.28100586 1.02880859]
start_recomend
start_recomend
[ 0.66503906  0.81274414  0.6315918  ... -0.28759766 -0.18774414
  0.56005859]
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
[ 0.65063477  0.79833984  0.6171875  ... -0.30224609 -0.20214844
  0.54638672]
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
[ 0.58618164  0.73388672  0.55273438 ... -0.3671875  -0.2668457
  0.48193359]
start_recomend
start_recomend
[ 0.84716797  0.99487305  0.81396484 ... -0.10546875 -0.00537109
  0.74316406]
start_recomend
start_recomend
[ 0.75170898  0.89916992  0.71826172 ... -0.20141602 -0.10131836
  0.6472168 ]
start_recomend
start_recomend
start

start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
[ 0.83349609  0.98071289  0.79980469 ... -0.11987305 -0.01953125
  0.72900391]
start_recomend
start_recomend
start_recomend
[ 0.79101562  0.93896484  0.75756836 ... -0.16186523 -0.06152344
  0.68676758]
start_recomend
[ 0.79150391  0.93945312  0.7578125  ... -0.16186523 -0.0612793
  0.68701172]
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
[ 0.8034668   0.95117188  0.77001953 ... -0.

start_recomend
start_recomend
start_recomend
[1.21484375 1.36230469 1.18115234 ... 0.26171875 0.36181641 1.11035156]
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
[1.28076172 1.42871094 1.24731445 ... 0.32788086 0.42797852 1.17651367]
start_recomend
start_recomend
[1.2565918  1.40478516 1.22363281 ... 0.30395508 0.40429688 1.15258789]
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
[1.30029297 1.44726562 1.26660156 ... 0.34643555 0.44702148 1.19580078]
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
[1.55859375 1.70629883 1.52514648 ... 0.60595703 0.70605469 1.45458984]
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_reco

[ 0.71606445  0.86376953  0.68237305 ... -0.23681641 -0.13671875
  0.61181641]
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
[ 0.57543945  0.72314453  0.54199219 ... -0.37744141 -0.27709961
  0.47119141]
start_recomend
start_recomend
[ 0.81762695  0.96533203  0.78442383 ... -0.13525391 -0.03491211
  0.71337891]
start_recomend
start_recomend
start_recomend
start_recomend
[ 0.67382812  0.8215332   0.64038086 ... -0.27929688 -0.17919922
  0.56958008]
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
[ 0.59887695  0.74633789  0.56518555 ... -0.35449219 -0.25415039
  0.49414062]
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
[ 0.72827148  0.87597656  0.69482422 ... -0.22436523 -0.12426758
  0.62402344]
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
[

start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
[ 0.57324219  0.72070312  0.53955078 ... -0.37988281 -0.27978516
  0.46875   ]
start_recomend
start_recomend
[ 0.48535156  0.6328125   0.45166016 ... -0.46777344 -0.36767578
  0.38085938]
start_recomend
start_recomend
start_recomend
start_recomend
[ 0.61499023  0.76269531  0.58154297 ... -0.33740234 -0.23730469
  0.51123047]
start_recomend
[ 0.89453125  1.04248047  0.86132812 ... -0.05859375  0.04150391
  0.7902832 ]
start_recomend
[ 0.66113281  0.80908203  0.62792969 ... -0.29199219 -0.19189453
  0.55664062]
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
[ 0.56298828  0.71044922  0.52929688 ... -0.39013672 -0.29003906
  0.45849609]
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
s

start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
[1.35693359 1.50439453 1.32324219 ... 0.40380859 0.50439453 1.25268555]
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
[1.12524414 1.27294922 1.09204102 ... 0.17236328 0.27294922 1.02148438]
start_recomend
start_recomend
[0.99438477 1.14208984 0.9609375  ... 0.04101562 0.14135742 0.89013672]
star

start_recomend
start_recomend
start_recomend
[1.65869141 1.80639648 1.625      ... 0.70605469 0.80615234 1.55419922]
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
[1.12524414 1.27294922 1.09204102 ... 0.17236328 0.27294922 1.02148438]
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
[1.31152344 1.45898438 1.27783203 ... 0.35839844 0.45849609 1.20703125]
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
[0.99438477 1.14208

start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
[ 0.59887695  0.74633789  0.56518555 ... -0.35449219 -0.25415039
  0.49414062]
start_recomend
start_recomend
start_recomend
start_recomend
[ 0.76782227  0.91552734  0.734375   ... -0.18505859 -0.0847168
  0.66357422]
start_recomend
start_recomend
start_recomend
[ 0.67382812  0.8215332   0.64038086 ... -0.27929688 -0.17919922
  0.56958008]
start_recomend
start_recomend
start_recomend
[1.08959961 1.23730469 1.05615234 ... 0.13647461 0.23681641 0.98535156]
start_recomend
start_recomend
start_recomend
start_recomend
[ 0.85986328  1.0078125   0.82641602 ... -0.09277344  0.00732422
  0.75537109]
start_recomend
start_recomend
[1.17407227 1.32177734 1.140625   ... 0.22167969 0.3215332  1.06982422]
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
[ 0.57543945  0.72314453  0.54199219 ... -0.37744141 -0.27709961
  0.47119141]
start_recomend
start_recomend
start_recome

start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
[ 0.65063477  0.79833984  0.6171875  ... -0.30224609 -0.20214844
  0.54638672]
start_recomend
start_recomend
[ 0.7421875   0.88964844  0.70874023 ... -0.21069336 -0.11035156
  0.63818359]
start_recomend
start_recomend
start_recomend
[ 0.59887695  0.74633789  0.56518555 ... -0.35449219 -0.25415039
  0.49414062]
start_recomend
[1.0144043  1.16210938 0.98095703 ... 0.06176758 0.16210938 0.91040039]
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
[1.10693359 1.25439453 1.07324219 ... 0.15380859 0.25390625 1.00244141]
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
start_recomend
star

In [ ]:
from recommenders.amazon_recommender import AmazonRecommender

amazon_recommender = AmazonRecommender()

amazon_tts_results = [['AmazonRecommender'] + list(evaluate_train_test_split_implicit(
    amazon_recommender, interactions_df, items_df))]

amazon_tts_results = pd.DataFrame(
    amazon_tts_results, columns=['Recommender', 'HR@1', 'HR@3', 'HR@5', 'HR@10', 'NDCG@1', 'NDCG@3', 'NDCG@5', 'NDCG@10'])

display(HTML(amazon_tts_results.to_html()))

In [ ]:
tts_results = pd.concat([linear_cbui_tts_results, amazon_tts_results]).reset_index(drop=True)
display(HTML(tts_results.to_html()))